site_name: SciEcon Publications
site_description: "research, innovation, and leadership in light of eastern and western philosophy the renaissance of Greek Academy and Confucius Schools"
repo_url: "https://github.com/SciEcon/SciEcon-Website/"

theme:
  palette: 
    scheme: default
  
  
  name: material
  custom_dir: overrides
  logo: assets/logo-dark-mode-v1.png
  favicon: assets/logo-light-mode-v1.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.integrate


nav:
  - Home: index.md
  - AMA: AMA.md
  - Research: Research.md
  - Innovate: Innovate.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

copyright: Hosted on the Internet Computer

extra_css:
  - stylesheets/extra.css
